package basic;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;

import javax.net.ssl.HttpsURLConnection;

import org.omg.CORBA.portable.InputStream;



public class Test {

	public static void main(String[] args) {
		
			// Your API Key and secret
			String apiKey = "sc3s45jzct6cpvs5mjs5wtj7";
			String Secret = "nKDdfukxeZ";
			// Signature is generated by SHA256 (Api-Key + Secret +
			// Timestamp (in seconds))
			String signature = org.apache.commons.codec.digest.DigestUtils
									 .sha256Hex(apiKey + Secret + System.currentTimeMillis() / 1000);

			
			System.out.println(signature);
		
	}
}

			// Example of call to the API
			/*String endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/status";
			URL url = new URL(endpoint);

			HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
			connection.setRequestProperty("X-Signature", signature);
			connection.setRequestProperty("Api-Key", apiKey);
			connection.setRequestProperty("Accept", "application/json");

			java.io.InputStream ins = connection.getInputStream();
			InputStreamReader isr = new InputStreamReader(ins);
			BufferedReader in = new BufferedReader(isr);

			String inputLine;
			while ((inputLine = in.readLine()) != null) {
						 System.out.println(inputLine);
			}
			in.close();

		} catch (Exception e) {
					e.printStackTrace();
		}
	}
*/

	
	
